improve include path to bpf_endian.h (#2936)
On fedora rawhide with clang 13, there are multiple false positve
test failures similar to

p4c/backends/ebpf/runtime/ebpf_kernel.h:28:10: fatal error:
  'bpf_endian.h' file not found

The libbfp-devel package installs bpf_endian.h to /usr/include/bpf/
The ./build_libbpf script installs it to
${CMAKE_CURRENT_SOURCE_DIR}/runtime/usr/include/bpf/

So the include should have a bpf/ prefix.
And since it is a system header the ""'s changed to <>'s