psa: Add missing new line in error message
This patch adds a missing new line between two error messages.

Before:

error: Package package PSA_Switch has no parameter named 'ingress'Are you using an up-to-date 'psa.p4'?

After:

error: Package package PSA_Switch has no parameter named 'ingress'
Are you using an up-to-date 'psa.p4'?

Signed-off-by: Radostin Stoyanov <rstoyanov@fedoraproject.org>