make: Add missing "dynamic_bitset.h" (#1011)
After commit da96f81 (Remove dependency on Judy1) the build fails with:

In file included from ../../include/bm/bm_sim/match_units.h:37,
                 from ../../include/bm/bm_sim/match_tables.h:34,
                 from ../../include/bm/bm_sim/tables.h:29,
                 from ../../include/bm/bm_sim/P4Objects.h:33,
                 from actions.cpp:25:
../../include/bm/bm_sim/handle_mgr.h:31:10: fatal error: dynamic_bitset.h: No such file or directory
   31 | #include "dynamic_bitset.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:580: actions.lo] Error 1
In file included from ../../include/bm/bm_sim/action_profile.h:35,
                 from action_profile.cpp:22:
../../include/bm/bm_sim/handle_mgr.h:31:10: fatal error: dynamic_bitset.h: No such file or directory
   31 | #include "dynamic_bitset.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Radostin Stoyanov <rstoyanov@fedoraproject.org>